/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq.tables;


import com.example.app.infrastructure.jooq.Keys;
import com.example.app.infrastructure.jooq.Public;
import com.example.app.infrastructure.jooq.tables.Users.UsersPath;
import com.example.app.infrastructure.jooq.tables.records.EmailVerificationsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailVerifications extends TableImpl<EmailVerificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.email_verifications</code>
     */
    public static final EmailVerifications EMAIL_VERIFICATIONS = new EmailVerifications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailVerificationsRecord> getRecordType() {
        return EmailVerificationsRecord.class;
    }

    /**
     * The column <code>public.email_verifications.verification_id</code>.
     */
    public final TableField<EmailVerificationsRecord, Long> VERIFICATION_ID = createField(DSL.name("verification_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.email_verifications.user_id</code>.
     */
    public final TableField<EmailVerificationsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.email_verifications.token</code>.
     */
    public final TableField<EmailVerificationsRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.email_verifications.expires_at</code>.
     */
    public final TableField<EmailVerificationsRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.email_verifications.created_at</code>.
     */
    public final TableField<EmailVerificationsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private EmailVerifications(Name alias, Table<EmailVerificationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmailVerifications(Name alias, Table<EmailVerificationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.email_verifications</code> table reference
     */
    public EmailVerifications(String alias) {
        this(DSL.name(alias), EMAIL_VERIFICATIONS);
    }

    /**
     * Create an aliased <code>public.email_verifications</code> table reference
     */
    public EmailVerifications(Name alias) {
        this(alias, EMAIL_VERIFICATIONS);
    }

    /**
     * Create a <code>public.email_verifications</code> table reference
     */
    public EmailVerifications() {
        this(DSL.name("email_verifications"), null);
    }

    public <O extends Record> EmailVerifications(Table<O> path, ForeignKey<O, EmailVerificationsRecord> childPath, InverseForeignKey<O, EmailVerificationsRecord> parentPath) {
        super(path, childPath, parentPath, EMAIL_VERIFICATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmailVerificationsPath extends EmailVerifications implements Path<EmailVerificationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmailVerificationsPath(Table<O> path, ForeignKey<O, EmailVerificationsRecord> childPath, InverseForeignKey<O, EmailVerificationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmailVerificationsPath(Name alias, Table<EmailVerificationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmailVerificationsPath as(String alias) {
            return new EmailVerificationsPath(DSL.name(alias), this);
        }

        @Override
        public EmailVerificationsPath as(Name alias) {
            return new EmailVerificationsPath(alias, this);
        }

        @Override
        public EmailVerificationsPath as(Table<?> alias) {
            return new EmailVerificationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EmailVerificationsRecord, Long> getIdentity() {
        return (Identity<EmailVerificationsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmailVerificationsRecord> getPrimaryKey() {
        return Keys.EMAIL_VERIFICATIONS_PKEY;
    }

    @Override
    public List<ForeignKey<EmailVerificationsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMAIL_VERIFICATIONS__EMAIL_VERIFICATIONS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.EMAIL_VERIFICATIONS__EMAIL_VERIFICATIONS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public EmailVerifications as(String alias) {
        return new EmailVerifications(DSL.name(alias), this);
    }

    @Override
    public EmailVerifications as(Name alias) {
        return new EmailVerifications(alias, this);
    }

    @Override
    public EmailVerifications as(Table<?> alias) {
        return new EmailVerifications(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailVerifications rename(String name) {
        return new EmailVerifications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailVerifications rename(Name name) {
        return new EmailVerifications(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailVerifications rename(Table<?> name) {
        return new EmailVerifications(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerifications where(Condition condition) {
        return new EmailVerifications(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerifications where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerifications where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerifications where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerifications where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerifications where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerifications where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerifications where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerifications whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerifications whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
