/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq.tables;


import com.example.app.infrastructure.jooq.Indexes;
import com.example.app.infrastructure.jooq.Keys;
import com.example.app.infrastructure.jooq.Public;
import com.example.app.infrastructure.jooq.tables.records.LoginAttemptsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoginAttempts extends TableImpl<LoginAttemptsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.login_attempts</code>
     */
    public static final LoginAttempts LOGIN_ATTEMPTS = new LoginAttempts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoginAttemptsRecord> getRecordType() {
        return LoginAttemptsRecord.class;
    }

    /**
     * The column <code>public.login_attempts.attempt_id</code>.
     */
    public final TableField<LoginAttemptsRecord, Long> ATTEMPT_ID = createField(DSL.name("attempt_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.login_attempts.email</code>.
     */
    public final TableField<LoginAttemptsRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<LoginAttemptsRecord, Object> IP_ADDRESS = createField(DSL.name("ip_address"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\""), this, "");

    /**
     * The column <code>public.login_attempts.user_agent</code>.
     */
    public final TableField<LoginAttemptsRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.login_attempts.attempt_time</code>.
     */
    public final TableField<LoginAttemptsRecord, OffsetDateTime> ATTEMPT_TIME = createField(DSL.name("attempt_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.login_attempts.success</code>.
     */
    public final TableField<LoginAttemptsRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.login_attempts.failure_reason</code>.
     */
    public final TableField<LoginAttemptsRecord, String> FAILURE_REASON = createField(DSL.name("failure_reason"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.login_attempts.user_id</code>.
     */
    public final TableField<LoginAttemptsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    private LoginAttempts(Name alias, Table<LoginAttemptsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LoginAttempts(Name alias, Table<LoginAttemptsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.login_attempts</code> table reference
     */
    public LoginAttempts(String alias) {
        this(DSL.name(alias), LOGIN_ATTEMPTS);
    }

    /**
     * Create an aliased <code>public.login_attempts</code> table reference
     */
    public LoginAttempts(Name alias) {
        this(alias, LOGIN_ATTEMPTS);
    }

    /**
     * Create a <code>public.login_attempts</code> table reference
     */
    public LoginAttempts() {
        this(DSL.name("login_attempts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LOGIN_ATTEMPTS_EMAIL_TIME);
    }

    @Override
    public Identity<LoginAttemptsRecord, Long> getIdentity() {
        return (Identity<LoginAttemptsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LoginAttemptsRecord> getPrimaryKey() {
        return Keys.LOGIN_ATTEMPTS_PKEY;
    }

    @Override
    public LoginAttempts as(String alias) {
        return new LoginAttempts(DSL.name(alias), this);
    }

    @Override
    public LoginAttempts as(Name alias) {
        return new LoginAttempts(alias, this);
    }

    @Override
    public LoginAttempts as(Table<?> alias) {
        return new LoginAttempts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LoginAttempts rename(String name) {
        return new LoginAttempts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoginAttempts rename(Name name) {
        return new LoginAttempts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoginAttempts rename(Table<?> name) {
        return new LoginAttempts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Condition condition) {
        return new LoginAttempts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
