/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq;


import com.example.app.infrastructure.jooq.tables.LoginAttempts;
import com.example.app.infrastructure.jooq.tables.RefreshTokens;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_LOGIN_ATTEMPTS_EMAIL_TIME = Internal.createIndex(DSL.name("idx_login_attempts_email_time"), LoginAttempts.LOGIN_ATTEMPTS, new OrderField[] { LoginAttempts.LOGIN_ATTEMPTS.EMAIL, LoginAttempts.LOGIN_ATTEMPTS.ATTEMPT_TIME }, false);
    public static final Index IDX_REFRESH_TOKENS_USER_ID = Internal.createIndex(DSL.name("idx_refresh_tokens_user_id"), RefreshTokens.REFRESH_TOKENS, new OrderField[] { RefreshTokens.REFRESH_TOKENS.USER_ID }, false);
}
