/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq;


import com.example.app.infrastructure.jooq.tables.EmailVerifications;
import com.example.app.infrastructure.jooq.tables.LoginAttempts;
import com.example.app.infrastructure.jooq.tables.RefreshTokens;
import com.example.app.infrastructure.jooq.tables.Users;
import com.example.app.infrastructure.jooq.tables.records.EmailVerificationsRecord;
import com.example.app.infrastructure.jooq.tables.records.LoginAttemptsRecord;
import com.example.app.infrastructure.jooq.tables.records.RefreshTokensRecord;
import com.example.app.infrastructure.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmailVerificationsRecord> EMAIL_VERIFICATIONS_PKEY = Internal.createUniqueKey(EmailVerifications.EMAIL_VERIFICATIONS, DSL.name("email_verifications_pkey"), new TableField[] { EmailVerifications.EMAIL_VERIFICATIONS.VERIFICATION_ID }, true);
    public static final UniqueKey<LoginAttemptsRecord> LOGIN_ATTEMPTS_PKEY = Internal.createUniqueKey(LoginAttempts.LOGIN_ATTEMPTS, DSL.name("login_attempts_pkey"), new TableField[] { LoginAttempts.LOGIN_ATTEMPTS.ATTEMPT_ID }, true);
    public static final UniqueKey<RefreshTokensRecord> REFRESH_TOKENS_PKEY = Internal.createUniqueKey(RefreshTokens.REFRESH_TOKENS, DSL.name("refresh_tokens_pkey"), new TableField[] { RefreshTokens.REFRESH_TOKENS.REFRESH_TOKEN_ID }, true);
    public static final UniqueKey<RefreshTokensRecord> REFRESH_TOKENS_TOKEN_KEY = Internal.createUniqueKey(RefreshTokens.REFRESH_TOKENS, DSL.name("refresh_tokens_token_key"), new TableField[] { RefreshTokens.REFRESH_TOKENS.TOKEN }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.USER_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmailVerificationsRecord, UsersRecord> EMAIL_VERIFICATIONS__EMAIL_VERIFICATIONS_USER_ID_FKEY = Internal.createForeignKey(EmailVerifications.EMAIL_VERIFICATIONS, DSL.name("email_verifications_user_id_fkey"), new TableField[] { EmailVerifications.EMAIL_VERIFICATIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.USER_ID }, true);
    public static final ForeignKey<RefreshTokensRecord, UsersRecord> REFRESH_TOKENS__REFRESH_TOKENS_USER_ID_FKEY = Internal.createForeignKey(RefreshTokens.REFRESH_TOKENS, DSL.name("refresh_tokens_user_id_fkey"), new TableField[] { RefreshTokens.REFRESH_TOKENS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.USER_ID }, true);
}
