/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq;


import com.example.app.infrastructure.jooq.tables.EmailVerifications;
import com.example.app.infrastructure.jooq.tables.LoginAttempts;
import com.example.app.infrastructure.jooq.tables.RefreshTokens;
import com.example.app.infrastructure.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.email_verifications</code>.
     */
    public static final EmailVerifications EMAIL_VERIFICATIONS = EmailVerifications.EMAIL_VERIFICATIONS;

    /**
     * The table <code>public.login_attempts</code>.
     */
    public static final LoginAttempts LOGIN_ATTEMPTS = LoginAttempts.LOGIN_ATTEMPTS;

    /**
     * The table <code>public.refresh_tokens</code>.
     */
    public static final RefreshTokens REFRESH_TOKENS = RefreshTokens.REFRESH_TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
