/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq.tables.records;


import com.example.app.infrastructure.jooq.tables.EmailVerifications;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailVerificationsRecord extends UpdatableRecordImpl<EmailVerificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.email_verifications.verification_id</code>.
     */
    public EmailVerificationsRecord setVerificationId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verifications.verification_id</code>.
     */
    public Long getVerificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.email_verifications.user_id</code>.
     */
    public EmailVerificationsRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verifications.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.email_verifications.token</code>.
     */
    public EmailVerificationsRecord setToken(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verifications.token</code>.
     */
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.email_verifications.expires_at</code>.
     */
    public EmailVerificationsRecord setExpiresAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verifications.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.email_verifications.created_at</code>.
     */
    public EmailVerificationsRecord setCreatedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verifications.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailVerificationsRecord
     */
    public EmailVerificationsRecord() {
        super(EmailVerifications.EMAIL_VERIFICATIONS);
    }

    /**
     * Create a detached, initialised EmailVerificationsRecord
     */
    public EmailVerificationsRecord(Long verificationId, Long userId, String token, OffsetDateTime expiresAt, OffsetDateTime createdAt) {
        super(EmailVerifications.EMAIL_VERIFICATIONS);

        setVerificationId(verificationId);
        setUserId(userId);
        setToken(token);
        setExpiresAt(expiresAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
