/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq.tables.records;


import com.example.app.infrastructure.jooq.tables.LoginAttempts;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoginAttemptsRecord extends UpdatableRecordImpl<LoginAttemptsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.login_attempts.attempt_id</code>.
     */
    public LoginAttemptsRecord setAttemptId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.attempt_id</code>.
     */
    public Long getAttemptId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.login_attempts.email</code>.
     */
    public LoginAttemptsRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public LoginAttemptsRecord setIpAddress(Object value) {
        set(2, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIpAddress() {
        return get(2);
    }

    /**
     * Setter for <code>public.login_attempts.user_agent</code>.
     */
    public LoginAttemptsRecord setUserAgent(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.login_attempts.attempt_time</code>.
     */
    public LoginAttemptsRecord setAttemptTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.attempt_time</code>.
     */
    public OffsetDateTime getAttemptTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.login_attempts.success</code>.
     */
    public LoginAttemptsRecord setSuccess(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.login_attempts.failure_reason</code>.
     */
    public LoginAttemptsRecord setFailureReason(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.failure_reason</code>.
     */
    public String getFailureReason() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.login_attempts.user_id</code>.
     */
    public LoginAttemptsRecord setUserId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.login_attempts.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoginAttemptsRecord
     */
    public LoginAttemptsRecord() {
        super(LoginAttempts.LOGIN_ATTEMPTS);
    }

    /**
     * Create a detached, initialised LoginAttemptsRecord
     */
    public LoginAttemptsRecord(Long attemptId, String email, Object ipAddress, String userAgent, OffsetDateTime attemptTime, Boolean success, String failureReason, Long userId) {
        super(LoginAttempts.LOGIN_ATTEMPTS);

        setAttemptId(attemptId);
        setEmail(email);
        setIpAddress(ipAddress);
        setUserAgent(userAgent);
        setAttemptTime(attemptTime);
        setSuccess(success);
        setFailureReason(failureReason);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
