/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq.tables.records;


import com.example.app.infrastructure.jooq.tables.RefreshTokens;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefreshTokensRecord extends UpdatableRecordImpl<RefreshTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.refresh_tokens.refresh_token_id</code>.
     */
    public RefreshTokensRecord setRefreshTokenId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.refresh_token_id</code>.
     */
    public Long getRefreshTokenId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.refresh_tokens.user_id</code>.
     */
    public RefreshTokensRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.refresh_tokens.token</code>.
     */
    public RefreshTokensRecord setToken(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.token</code>.
     */
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.refresh_tokens.expires_at</code>.
     */
    public RefreshTokensRecord setExpiresAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.refresh_tokens.revoked</code>.
     */
    public RefreshTokensRecord setRevoked(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.refresh_tokens.created_at</code>.
     */
    public RefreshTokensRecord setCreatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokensRecord
     */
    public RefreshTokensRecord() {
        super(RefreshTokens.REFRESH_TOKENS);
    }

    /**
     * Create a detached, initialised RefreshTokensRecord
     */
    public RefreshTokensRecord(Long refreshTokenId, Long userId, String token, OffsetDateTime expiresAt, Boolean revoked, OffsetDateTime createdAt) {
        super(RefreshTokens.REFRESH_TOKENS);

        setRefreshTokenId(refreshTokenId);
        setUserId(userId);
        setToken(token);
        setExpiresAt(expiresAt);
        setRevoked(revoked);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
