/*
 * This file is generated by jOOQ.
 */
package com.example.app.infrastructure.jooq.tables.records;


import com.example.app.infrastructure.jooq.tables.Users;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.user_id</code>.
     */
    public UsersRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.password_hash</code>.
     */
    public UsersRecord setPasswordHash(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.role</code>.
     */
    public UsersRecord setRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.is_active</code>.
     */
    public UsersRecord setIsActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.users.is_email_verified</code>.
     */
    public UsersRecord setIsEmailVerified(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users.is_email_verified</code>.
     */
    public Boolean getIsEmailVerified() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.users.display_name</code>.
     */
    public UsersRecord setDisplayName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.users.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.version</code>.
     */
    public UsersRecord setVersion(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.users.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long userId, String email, String passwordHash, String role, Boolean isActive, Boolean isEmailVerified, String displayName, Integer version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Users.USERS);

        setUserId(userId);
        setEmail(email);
        setPasswordHash(passwordHash);
        setRole(role);
        setIsActive(isActive);
        setIsEmailVerified(isEmailVerified);
        setDisplayName(displayName);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
